[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/metal-recycling*"
  to = "/metal-recycling"

[[redirects]]
  from = "/waste-recycling*"
  to = "/waste-recycling"

[[redirects]]
  from = "/contact-jain-hydraulics"
  to = "/contact"

[[redirects]]
  from = "/about-jain-hydraulics"
  to = "/about"

[[redirects]]
  from = "/vision-jain-hydraulics"
  to = "/about"

[[redirects]]
  from = "/baling-press-continuous*"
  to = "/products/balers/continuous"

[[redirects]]
  from = "/shredder*"
  to = "/products/shredders/"
  
[[redirects]]
  from = "/baling-press-super*"
  to = "/products/balers/super-jumbo"

[[redirects]]
  from = "/baling-press-horizontal*"
  to = "/products/balers/horizontal/"

[[redirects]]
  from = "/baling-press-jumbo-automatic*"
  to = "/products/balers/jumbo-automatic/"

[[redirects]]
  from = "/baling-press-jumbo-plc*"
  to = "/products/balers/jumbo-plc/"

[[redirects]]
  from = "/baling-press-mini-automatic*"
  to = "/products/balers/mini-automatic/"

[[redirects]]
  from = "/baling-press-mini-plc*"
  to = "/products/balers/mini-plc/"

[[redirects]]
  from = "/baling-press-super*"
  to = "/products/balers/super-jumbo/"

[[redirects]]
  from = "/baler-double*"
  to = "/products/balers/double-action/"

[[redirects]]
  from = "/baler-vertical*"
  to = "/products/balers/vertical"

[[redirects]]
  from = "/baling-press-double*"
  to = "/products/balers/double-action/"

[[redirects]]
  from = "/sheraing-machine-alligator*"
  to = "/products/shears/alligator"

[[redirects]]
  from = "/nibbler*"
  to = "/products/shears/nibbling"

[[redirects]]
  from = "/box*"
  to = "/products/shears/box"

[[redirects]]
  from = "/jhpl*"
  to = "/"

[[redirects]]
  from = "/briquette*"
  to = "/products/cranes-and-chip-processing/briquetting"

[[redirects]]
  from = "/baling-press-triple-action*"
  to = "/products/balers/triple-action"

[[redirects]]
  from = "/baling-press-jumbo-triple-action"
  to = "/products/balers/triple-action"

[[redirects]]
  from = "/briquette*"
  to = "/products/cranes-and-chip-processing/briquetting"

[[redirects]]
  from = "/sheraing-machine-metal-scrap"
  to = "/products/shears"

[[redirects]]
  from = "/baling-press-jumbo-triple-action"
  to = "/products/balers/triple-action"
  
[[redirects]]
  from = "/products/balers/high%20density"
  to = "/products/balers/high-density"

[[redirects]]
  from = "/products/balers/jumbo%20manual"
  to = "/products/balers/jumbo-manual"

[[redirects]]
  from = "/products/balers/jumbo%20plc"
  to = "/products/balers/jumbo-plc"

[[redirects]]
  from = "/products/balers/manual%20mini"
  to = "/products/balers/manual-mini"

[[redirects]]
  from = "/products/balers/mini%20plc"
  to = "/products/balers/mini-plc"

[[redirects]]
  from = "/products/balers/super%20jumbo"
  to = "/products/balers/super-jumbo"

[[redirects]]
  from = "/products/balers/triple%20action"
  to = "/products/balers/triple-action"

[[redirects]]
  from = "/products/balers/vertical"
  to = "/products/balers/vertical"

[[redirects]]
  from = "/products/balers/double%20action"
  to = "/products/balers/double-action"

[[redirects]]
  from = "/products/shredders/hammer%20mill"
  to = "/products/shredders/hammer-mill"
  
[[redirects]]
  from = "/products/shredders/twin%20shaft"
  to = "/products/shredders/twin-shaft"

[[redirects]]
  from = "/metal%20recycling"
  to = "/metal-recycling"
  
[[redirects]]
  from = "/waste%20recycling"
  to = "/waste-recycling"

[[redirects]]
  from = "/products/cranes%20and%20chip%20processing/briquetting"
  to = "/products/cranes-and-chip-processing/briquetting"
  
[[redirects]]
  from = "/products/cranes%20and%20chip%20processing/rotating%20tower%20crane"
  to = "/products/cranes-and-chip-processing/rotating-tower-crane"

[[redirects]]
  from = "/products/cranes%20and%20chip%20processing/grabber"
  to = "/products/cranes-and-chip-processing/grabber"

